---

- name: Test distribution
  assert:
    that:
      ansible_os_family in [
          'RedHat',
          'Debian',
          'Ubuntu',
          'Linuxmint',
      ]

- include: package.yaml
  tags: [ 'role::sudo:package' ]

- name: Combine definition lists
  set_fact:
    sudo_defaults_combined: '{{
      (sudo_defaults | list) +
      (sudo_defaults_group | list) +
      (sudo_defaults_host | list) }}'
    sudo_users_combined: '{{
      (sudo_users | list) +
      (sudo_users_group | list) +
      (sudo_users_host | list) }}'

- name: Create /etc/sudoers file
  template:
    src: 'sudoers.j2'
    dest: '/etc/sudoers'
    owner: 'root'
    group: 'root'
    mode: 0640
    validate: '{{ sudo_visudo }} -cf %s'
  tags: [ 'role::sudo:config' ]
